#version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/main
    environment:
      FLASK_APP: main.py

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - log_destination=stderr
      - logging_collector=on
    ports:
      - "5432:5432"
    volumes:
      - ./database/:/var/lib/postgresql/data